# Generated by Django 6.0.5 on 2026-06-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_tickets_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='tarjeta',
            field=models.CharField(blank=True, choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='tipo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('BANCO', 'Banco'), ('QR', 'QR')], max_length=20),
        ),
    ]
